import { useNavigate } from 'react-router-dom';
import { getAIFixes } from '../api';
import { useFetch } from '../hooks/useFetch';
import { Loading, ErrorBox, EmptyState } from '../components/Loading';

function prStatusColor(status: string): string {
  switch (status) {
    case 'Open': return 'var(--green)';
    case 'Merged': return 'var(--accent)';
    case 'Closed': return 'var(--text-muted)';
    case 'Failed': return 'var(--red)';
    case 'NoPR': return 'var(--orange)';
    default: return 'var(--text-muted)';
  }
}

export default function FixesPage() {
  const navigate = useNavigate();
  const { data, loading, error } = useFetch(() => getAIFixes(100), []);

  if (loading) return <Loading message="Loading AI fixes..." />;
  if (error) return <ErrorBox message={`Failed to load fixes: ${error}`} />;

  const fixes = data?.fixes ?? [];

  if (fixes.length === 0) {
    return (
      <EmptyState
        title="No AI Fixes Yet"
        message="No fixes have been generated by AI yet. Trigger analysis on a crash bucket to generate fixes."
        action={{ label: 'View AI Analysis', onClick: () => navigate('/ai-analysis') }}
      />
    );
  }

  const open = fixes.filter(f => f.prStatus === 'Open').length;
  const merged = fixes.filter(f => f.prStatus === 'Merged').length;
  const noPr = fixes.filter(f => f.prStatus === 'NoPR').length;

  return (
    <>
      <div className="page-header">
        <h2>AI-Generated Fixes</h2>
        <p>{fixes.length} fix(es) generated</p>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-label">Total Fixes</div>
          <div className="stat-value">{fixes.length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">PRs Open</div>
          <div className="stat-value" style={{ color: 'var(--green)' }}>{open}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">PRs Merged</div>
          <div className="stat-value" style={{ color: 'var(--accent)' }}>{merged}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Local Only</div>
          <div className="stat-value" style={{ color: 'var(--orange)' }}>{noPr}</div>
        </div>
      </div>

      <div className="table-container">
        <table>
          <thead>
            <tr>
              <th>Fix ID</th>
              <th>Bucket</th>
              <th>Branch</th>
              <th>PR Status</th>
              <th>PR</th>
              <th>Description</th>
              <th>Created</th>
            </tr>
          </thead>
          <tbody>
            {fixes.map((f) => (
              <tr key={f.fixId} onClick={() => navigate(`/buckets/${f.bucketId}`)} style={{ cursor: 'pointer' }}>
                <td className="mono" style={{ fontSize: 11 }}>{f.fixId.slice(0, 16)}...</td>
                <td className="mono" style={{ fontSize: 11 }}>{f.bucketId.slice(0, 12)}...</td>
                <td className="mono" style={{ fontSize: 11 }}>{f.branchName ?? '—'}</td>
                <td>
                  <span style={{
                    display: 'inline-block', padding: '2px 8px', borderRadius: 4,
                    fontSize: 11, fontWeight: 600,
                    background: `${prStatusColor(f.prStatus)}22`,
                    color: prStatusColor(f.prStatus),
                  }}>
                    {f.prStatus}
                  </span>
                </td>
                <td>
                  {f.prUrl ? (
                    <a href={f.prUrl} target="_blank" rel="noopener noreferrer"
                       onClick={(e) => e.stopPropagation()}
                       style={{ fontSize: 12 }}>
                      #{f.prNumber}
                    </a>
                  ) : <span style={{ color: 'var(--text-muted)', fontSize: 12 }}>—</span>}
                </td>
                <td className="truncate" style={{ maxWidth: 300, fontSize: 12 }}>
                  {f.fixDescription ?? f.prTitle ?? '—'}
                </td>
                <td style={{ whiteSpace: 'nowrap', fontSize: 12 }}>
                  {new Date(f.createdAtUtc).toLocaleString()}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
